"""Add new Visit fields and indices

Revision ID: 21cc284e0820
Revises: 
Create Date: 2026-01-04 19:45:54.712721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cc284e0820'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_article')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('date_submitted',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('views',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cover_image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('document_filename',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index('idx_article_date_posted', ['date_posted'], unique=False)
        batch_op.create_index('idx_article_status_category', ['status', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_status'), ['status'], unique=False)
        batch_op.drop_column('approved')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_comment_article_date', ['article_id', 'date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_parent_id'), ['parent_id'], unique=False)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('visitor_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('referer', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_visit_article_date', ['article_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_visit_hash_date', ['visitor_hash', 'timestamp'], unique=False)
        batch_op.create_index('idx_visit_session_date', ['session_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_visit_user_date', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_visitor_hash'), ['visitor_hash'], unique=False)
        batch_op.create_foreign_key('fk_visit_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_visit_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_visit_visitor_hash'))
        batch_op.drop_index(batch_op.f('ix_visit_user_id'))
        batch_op.drop_index(batch_op.f('ix_visit_timestamp'))
        batch_op.drop_index(batch_op.f('ix_visit_session_id'))
        batch_op.drop_index(batch_op.f('ix_visit_article_id'))
        batch_op.drop_index('idx_visit_user_date')
        batch_op.drop_index('idx_visit_session_date')
        batch_op.drop_index('idx_visit_hash_date')
        batch_op.drop_index('idx_visit_article_date')
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('referer')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('visitor_hash')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('session_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comment_article_id'))
        batch_op.drop_index('idx_comment_article_date')
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_article_status'))
        batch_op.drop_index(batch_op.f('ix_article_category'))
        batch_op.drop_index('idx_article_status_category')
        batch_op.drop_index('idx_article_date_posted')
        batch_op.alter_column('document_filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('cover_image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('views',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_submitted',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    op.create_table('_alembic_tmp_article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('likes', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_submitted', sa.DATETIME(), nullable=False),
    sa.Column('cover_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('document_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('views', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
