"""Add soft deletes and draft support

Revision ID: 735890a81e2b
Revises: 21cc284e0820
Create Date: 2026-01-04 19:53:36.070920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735890a81e2b'
down_revision = '21cc284e0820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index('idx_article_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_article_is_draft', ['is_draft'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_comment_deleted_at', ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_deleted_at')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('idx_article_is_draft')
        batch_op.drop_index('idx_article_deleted_at')
        batch_op.drop_column('is_draft')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
